name: build-deploy-aladin-starcharts
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install node packages
        run: npm install
      - name: build aladin-starcharts
        run: npm run build
        env:
           CI: ""

      - name: upload files to webserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          rm: true
          source: "build"
          target: "~/www/repository/aladin-starcharts"

      - name: move files to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USER }}
          password: ${{ secrets.MY_PASSWORD }}
          script: |
             cd ~/www/aladin-starcharts
             cp ~/www/repository/aladin-starcharts/build/*.* .
             cp -r ~/www/repository/aladin-starcharts/build/static/* ~/www/my_static_files